name: Merge any release branch to uat
on:
  push:
    branches:
      - 'master'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master to version_4.2.1
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          target_branch: version_4.2.1
          github_token: ${{ github.token }}
